# Generated by Django 3.1.14 on 2022-12-01 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Имя покемона')),
                ('title_jp', models.CharField(blank=True, max_length=200, verbose_name='Имя покемона на японском')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Имя покемона на английском')),
                ('image', models.ImageField(null=True, upload_to='pictures', verbose_name='Изображение покемона')),
                ('description', models.TextField(blank=True, max_length=350, verbose_name='Описание покемона')),
                ('previous_evolution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_evolution', to='pokemon_entities.pokemon', verbose_name='Из кого эволюционировал покемон')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lat', models.FloatField(verbose_name='Координаты: широта')),
                ('Lon', models.FloatField(verbose_name='Координаты: долгота')),
                ('Appeared_at', models.DateTimeField(verbose_name='Время появления')),
                ('Disappeared_at', models.DateTimeField(verbose_name='Время исчезновения')),
                ('Level', models.IntegerField(blank=True, null=True, verbose_name='Уровень')),
                ('Health', models.IntegerField(blank=True, null=True, verbose_name='Здоровье')),
                ('Strength', models.IntegerField(blank=True, null=True, verbose_name='Сила')),
                ('Defence', models.IntegerField(blank=True, null=True, verbose_name='Защита')),
                ('Stamina', models.IntegerField(blank=True, null=True, verbose_name='Выносливость')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_entities.pokemon', verbose_name='Покемон')),
            ],
        ),
    ]
