# Generated by Django 3.1.14 on 2022-12-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0005_pokemonelementtype_element_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonelementtype',
            name='strong_against',
            field=models.ManyToManyField(blank=True, null=True, related_name='weak_against', to='pokemon_entities.PokemonElementType', verbose_name='Силён против'),
        ),
    ]
